import os
import shutil
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Set

from setuptools import Command

from buildkit.utils import get_cpy_suffix


TEMP_BUILD_DIR = os.environ.get("BUILD_TEMP_DIR", ".build_package_tmp")

# Default suffix patterns that will be removed by the clean command.
# Compiled suffix needs to be detected dynamically for cross-platform support.
_DEFAULT_COMPILED_SUFFIX = get_cpy_suffix()
DEFAULT_SUFFIX_PATTERNS: Sequence[str] = (
    "*.c",
    f"*{_DEFAULT_COMPILED_SUFFIX}" if _DEFAULT_COMPILED_SUFFIX else "*.so",
    "*.so",
    "*.pyd",
)


def normalize_patterns(patterns: Sequence[str]) -> List[str]:
    seen: Set[str] = set()
    normalized: List[str] = []
    for pattern in patterns:
        if not pattern:
            continue
        value = pattern.strip()
        if not value:
            continue
        if value.startswith('.'):
            value = f"*{value}"
        if value not in seen:
            seen.add(value)
            normalized.append(value)
    return normalized


def iter_matched_files(patterns: Sequence[str], base_path: Path = Path(".")) -> List[Path]:
    """Return a list of files matching the provided glob patterns."""

    base_path = Path(base_path)
    matched: Set[Path] = set()
    for pattern in normalize_patterns(patterns):
        for path in base_path.rglob(pattern):
            if path.is_file():
                matched.add(path)
    return sorted(matched)


def remove_files(files: Iterable[Path]) -> List[Path]:
    """Remove the provided files and return the successfully deleted ones."""

    removed: List[Path] = []
    for file_path in files:
        try:
            resolved = Path(file_path)
            resolved.unlink()
            removed.append(resolved)
            print(f"🗑 Removed {file_path}")
        except FileNotFoundError:
            continue
        except Exception as exc:  # pragma: no cover - log unexpected errors
            print(f"⚠ Failed to remove {file_path}: {exc}")
    return removed


class CleanCommand(Command):
    """Clean build artifacts such as .c, .so/.pyd files and build directories."""

    description = "Clean build artifacts generated by buildkit and setuptools"
    user_options = [
        (
            "suffixes=",
            None,
            "Comma separated glob patterns for files to remove (default: *.c, *.so, *.pyd)",
        )
    ]

    def initialize_options(self):
        self.suffixes: Optional[Sequence[str]] = None
        self._patterns: List[str] = list(DEFAULT_SUFFIX_PATTERNS)

    def finalize_options(self):
        if self.suffixes is None:
            env_suffixes = os.environ.get("BUILD_CLEAN_SUFFIXES")
            if env_suffixes:
                self.suffixes = env_suffixes

        if isinstance(self.suffixes, str):
            parsed = [part.strip() for part in self.suffixes.split(",") if part.strip()]
            self._patterns = normalize_patterns(parsed or DEFAULT_SUFFIX_PATTERNS)
        elif self.suffixes is None:
            self._patterns = list(normalize_patterns(DEFAULT_SUFFIX_PATTERNS))
        else:
            self._patterns = normalize_patterns(list(self.suffixes))

    def set_suffixes(self, suffixes: Sequence[str]):
        """Allow programmatic configuration of suffix patterns."""

        self._patterns = normalize_patterns(suffixes)

    def run(self):
        matched_files = iter_matched_files(self._patterns)
        remove_files(matched_files)
        shutil.rmtree("build", ignore_errors=True)
        shutil.rmtree(TEMP_BUILD_DIR, ignore_errors=True)
